language: minimal

sudo: required

services:
  - docker

jobs:
  include:
    - stage: unit tests
      script: make test
    - stage: deploy to dev
      script: make deploy
      env:
        - DOMAIN_NAME=dev-sls.$DOMAIN_NAME
        - ENV=dev
        - REALM=nonprod
      deploy:
        provider: script
    - stage: deploy to production
      script: make deploy
      env:
        - DOMAIN_NAME=www.$DOMAIN_NAME
        - ENV=prod
        - REALM=prodprod
      on:
          branch: master
      deploy:
        provider: script