language: minimal

sudo: required

services:
  - docker

notifications:
  slack: $SLACK

jobs:
  include:
    - stage: unit tests
      script: make test
    - stage: deploy to dev
      script: make deploy
      env:
        - DOMAIN_NAME=dev-sls.$DOMAIN_NAME
        - ENV=dev
        - REALM=nonprod
    - stage: deploy to production
      script: make deploy
      env:
        - DOMAIN_NAME=www.$DOMAIN_NAME
        - ENV=production
        - REALM=prod
      on:
          branch: master