language: minimal

sudo: required

services:
  - docker

jobs:
  include:
    - stage: unit tests
      script: make test
      notifications:
        slack: $SLACK
    - stage: deploy to dev
      script: make deploy
      env:
        - DOMAIN_NAME=dev-sls.$DOMAIN_NAME
        - ENV=dev
        - REALM=nonprod
      notifications:
        slack: $SLACK
    - stage: deploy to production
      script: make deploy
      env:
        - DOMAIN_NAME=www.$DOMAIN_NAME
        - ENV=production
        - REALM=prod
      notifications:
        slack: $SLACK
      on:
          branch: master